<center><h1 style="color:#D4AF37"> ‚ö°‚ö° AEMR Outage Data Analysis Using SQL ‚ö°‚ö°</h1>

<img src = "https://images.squarespace-cdn.com/content/v1/551972d8e4b0d571edc2e2c8/8f3abd33-0916-4415-9b24-593eea1d1e3c/Screen+Shot+2022-04-20+at+12.41.24+PM.png">

  
Apply SQL to analyse data for the American Energy Market Regulator (AEMR).

The analytics team has supplied you with the following table extract that contains all the data you need to analyse for the `AEMR` outages. 

<li> AEMR_Outage_Table </li>

<h1 style="color:#D4AF37"> What's the Business Problem? üí∞</h1>

The American Energy Market Regulator (AEMR) is responsible for looking after the
United States of America‚Äôs domestic energy network. The regulator‚Äôs responsibility is to
ensure that America‚Äôs energy network remains reliable with minimal disruptions, which
are known as outages. 

There are four key types of outages:

‚óè Consequential

‚óè Forced 

‚óè Opportunistic 

‚óè Planned 

Recently, the AEMR management team has been increasingly aware of a large number
of energy providers that submitted outages over the 2016 and 2017 calendar years. The
management team has expressed a desire to have the following two areas of concern
addressed:

<b> A) Energy Stability and Market Outages
    <p>
B) Energy Losses and Market Reliability </b>

As an analyst within the data and reporting team, I have been asked to address these
two immediate areas of concern, and provide insights that may be of interest to the management team.

<h3 style="color:#D4AF37">  SQLite Refresher ‚öôÔ∏è </h3>

The data has been pro-loaded to access in the `AEMR.db`. SQL queries will be stored in this notebook as a reference when reviewing data analysis in Tableau. </b>.

In [206]:
%%capture
!pip install ipython-sql sqlalchemy
import sqlalchemy
sqlalchemy.create_engine("sqlite:///AEMR.db")
%load_ext sql
%sql sqlite:///AEMR.db

In [207]:
%%js
require(['notebook/js/codecell'], function (codecell) {
    codecell.CodeCell.options_default.highlight_modes['magic_text/x-mssql'] = { 'reg': [/%?%sql/] };
    Jupyter.notebook.events.one('kernel_ready.Kernel', function () {
        Jupyter.notebook.get_cells().map(function (cell) {
            if (cell.cell_type == 'code') { cell.auto_highlight(); }
        });
    });
});

In [245]:
%%sql

SELECT *
FROM AEMR_Outage_Table
LIMIT 2;

 * sqlite:///AEMR.db
Done.

[(1, '2017-12-28 06:00', '2017-12-28 10:00', 2017, 12, 'DNHR_DENMARK_WF1', 'DNHR', 'Approved', 'Consequential', 1.44, 'a network outage in Denmark caused the windfarm to trip at 6:26 am'),
 (2, '2017-12-26 09:00', '2017-12-27 00:00', 2017, 12, 'COLLGAR_WF1', 'COLLGAR', 'Approved', 'Forced', 30.0, 'Forced Outage - BS on Overhead line pole S-81 - CG10/11')]

<h3 style="color:#D4AF37"> ‚ö° Part I. Energy Stability & Market Outages ‚ö° </h3>

Energy stability is one of the key themes the AEMR management team cares about. To ensure energy security and reliability, AEMR needs to understand the following:
<p>
<b>

<li> What are the most common outage types and how long do they tend to last? 
<li> How frequently do the outages occur? 
<li> Are there any energy providers which have more outages than their peers which may be indicative of being unreliable? 
    
<p>

<u style="color:Green"> Please note that throughout the entire case study, we are interested ONLY in the Outages where Status = Approved. Please ignore other types of Outages such as cancelled or not approved.</u>

<h3 style="color:#D4AF37"> Question One </h3> 

<b> Write a SQL Statement to `COUNT` the number of valid (i.e. `Status = Approved`) Outage Events sorted by their respective `Outage_Reason` (i.e. `Forced`, `Consequential`, `Scheduled`, `Opportunistic`) over the 2016 & 2017 Periods. </b>

Do we notice anything regarding the trends for specific Outages over the 2016 / 2017 Period?

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [247]:
%%sql
SELECT COUNT(*) as Total_Number_Outages,
Outage_Reason,
Year
FROM AEMR_Outage_Table
WHERE Status = 'Approved'
GROUP BY Outage_Reason, Year
ORDER BY Year;

 * sqlite:///AEMR.db
Done.

[(181, 'Consequential', 2016),
 (1264, 'Forced', 2016),
 (106, 'Opportunistic Maintenance (Planned)', 2016),
 (380, 'Scheduled (Planned)', 2016),
 (127, 'Consequential', 2017),
 (1622, 'Forced', 2017),
 (102, 'Opportunistic Maintenance (Planned)', 2017),
 (320, 'Scheduled (Planned)', 2017)]

<h4 style = "color:#5D3FD3">Finding of trends: Based on the total # of outages, Forced outage is the most common one.</h4>

<h3 style="color:#D4AF37"> Question Two </h3>

<b> i) Write a SQL Statement showing the `Total` of all Outage Types (Forced, Consequential, Scheduled, Opportunistic) where the `Status = Approved`, that occurred for both 2016 and 2017, grouped by `Year` and `Month`.  per month (i.e. 1 ‚Äì 12). Order by `Year`, `Month`, `Total_Number_Outages` in Descending Order.


ii) Building on the query you write in i), group the results by `Outage Type`, `Year` and `Month`. This is so you can identify whether there is any outage type specifically increasing on a monthly basis when comparing 2016 to 2017. </b>


<b>‚ö†Ô∏èHint: You might find it helpful to create a small Common Table Expression to address these two questions! </b>

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [249]:
%%sql
SELECT Year, Month, Outage_Reason, COUNT(*)as Total_Number_Outages

FROM AEMR_Outage_Table

WHERE Status = 'Approved'
GROUP BY Month, Outage_Reason;

 * sqlite:///AEMR.db
Done.

[(2017, 1, 'Consequential', 36),
 (2017, 1, 'Forced', 204),
 (2017, 1, 'Opportunistic Maintenance (Planned)', 18),
 (2017, 1, 'Scheduled (Planned)', 36),
 (2017, 2, 'Consequential', 50),
 (2017, 2, 'Forced', 246),
 (2017, 2, 'Opportunistic Maintenance (Planned)', 18),
 (2017, 2, 'Scheduled (Planned)', 63),
 (2017, 3, 'Consequential', 26),
 (2017, 3, 'Forced', 147),
 (2017, 3, 'Opportunistic Maintenance (Planned)', 21),
 (2017, 3, 'Scheduled (Planned)', 51),
 (2017, 4, 'Consequential', 12),
 (2017, 4, 'Forced', 159),
 (2017, 4, 'Opportunistic Maintenance (Planned)', 11),
 (2017, 4, 'Scheduled (Planned)', 79),
 (2017, 5, 'Consequential', 41),
 (2017, 5, 'Forced', 206),
 (2017, 5, 'Opportunistic Maintenance (Planned)', 13),
 (2017, 5, 'Scheduled (Planned)', 80),
 (2017, 6, 'Consequential', 20),
 (2017, 6, 'Forced', 284),
 (2017, 6, 'Opportunistic Maintenance (Planned)', 21),
 (2017, 6, 'Scheduled (Planned)', 47),
 (2017, 7, 'Consequential', 24),
 (2017, 7, 'Forced', 262),
 (2017, 7, 'Opportunistic Maintenance (Planned)', 18),
 (2017, 7, 'Scheduled (Planned)', 53),
 (2017, 8, 'Consequential', 8),
 (2017, 8, 'Forced', 322),
 (2017, 8, 'Opportunistic Maintenance (Planned)', 21),
 (2017, 8, 'Scheduled (Planned)', 52),
 (2017, 9, 'Consequential', 11),
 (2017, 9, 'Forced', 233),
 (2017, 9, 'Opportunistic Maintenance (Planned)', 18),
 (2017, 9, 'Scheduled (Planned)', 34),
 (2017, 10, 'Consequential', 26),
 (2017, 10, 'Forced', 274),
 (2017, 10, 'Opportunistic Maintenance (Planned)', 13),
 (2017, 10, 'Scheduled (Planned)', 87),
 (2017, 11, 'Consequential', 34),
 (2017, 11, 'Forced', 272),
 (2017, 11, 'Opportunistic Maintenance (Planned)', 23),
 (2017, 11, 'Scheduled (Planned)', 68),
 (2017, 12, 'Consequential', 20),
 (2017, 12, 'Forced', 277),
 (2017, 12, 'Opportunistic Maintenance (Planned)', 13),
 (2017, 12, 'Scheduled (Planned)', 50)]

In [251]:
%%sql
SELECT Year, COUNT(*)as Total_Number_Outages

FROM AEMR_Outage_Table

WHERE Outage_Reason = 'Forced'
GROUP BY Year;

 * sqlite:///AEMR.db
Done.

[(2016, 1346), (2017, 1817)]

<h4 style = "color:#5D3FD3"> Findings: total number of outage events is rapidly increasing from 2016 to 2017, especially among the forced outage type.</h4>

Hmm. Interesting. We've now identified a specific outage type is rapidly increasing from 2016 to 2017. However, frequency is just one aspect we care about. We also care about the <b> `duration` </b> of our ouatges.

In other words, if an outage is very short, we aren't as concerned. However, if the outage is very long, this then has the risk of threatening our energy supplies. We want to identify the problematic energy providers here. This leads us to our next question below.

<h3 style="color:#D4AF37"> Question Three </h3>

<b>Write a SQL statement that calculates 1) The `Total_Number_Outage_Events` and 2) The <b> `Average Duration`</b> in <u>DAYS</u> for each `Participant Code` and `Outage Type` over the 2016 and 2017 Period where the `Status = Approved`. 
Order by `Total_Number_Outage_Events` in Descending Order, `Reason` and `Year`.  </b>

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [253]:
%%sql
SELECT
Participant_Code, 
COUNT(*) as Total_Number_Outage_Events,
ROUND(AVG((ABS(JULIANDAY(End_Time) - JULIANDAY(Start_Time)))),2) as Average_Outage_Duration_In_Days

FROM AEMR_Outage_Table
WHERE Outage_Reason = 'Forced'

GROUP BY Participant_Code
ORDER BY Average_Outage_Duration_In_Days DESC
LIMIT 8;

 * sqlite:///AEMR.db
Done.

[('EUCT', 25, 2.78),
 ('WGUTD', 11, 2.6),
 ('ENRG', 34, 1.61),
 ('MELK', 350, 1.57),
 ('COLLGAR', 95, 1.11),
 ('PJRH', 156, 1.06),
 ('KORL', 132, 0.96),
 ('GW', 561, 0.65)]

Now we're getting somewhere...!
We've identified participants who are having many outages, as well as participants who have been offline for the longest durations.

Armed with this information, it's important we're able to classify our participants accordingly based on reliability metrics of uptime.

We classify a participant based off the following criteria:
<b>
<li> High Risk - On average, the participant is unavailable for > 24 Hours (1 Day)</li>
<li> Medium Risk - On average, the participant is unavailable between 12 and 24 Hours </li>
<li> Low Risk - On average, the participant is unavailable for less than 12 Hours</li> 
</b>

<h3 style="color:#D4AF37"> Question Four </h3>

<b> Using the above criteria for context, write a SQL Statement that <u> classifies each participant code as either `High Risk`, `Medium Risk` or `Low Risk` in a column called `Risk_Classification`</u> that is based off their Average Outage Duration Time. Please note that this is for all valid (i.e. `Where status = approved`) outage types (Forced, Consequential, Scheduled, Opportunistic) for <u>all</u> participant codes from 2016 to 2017. Order the results using `Average Duration Time In Days` in descending order.

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [255]:
%%sql
WITH CTE_risk AS(
SELECT
Participant_Code, 
Year, 
COUNT(*) as Total_Number_Outage_Events,
ROUND(AVG((ABS(JULIANDAY(End_Time) - JULIANDAY(Start_Time)))),2) as Average_Outage_Duration_In_Days

FROM AEMR_Outage_Table
WHERE Outage_Reason = 'Forced'

GROUP BY Outage_Reason, Year, Participant_Code
ORDER BY Total_Number_Outage_Events DESC
)

SELECT *,
CASE
    WHEN Average_Outage_Duration_In_Days >= 1 THEN 'High Risk'
    WHEN Average_Outage_Duration_In_Days BETWEEN 0.5 AND 1 THEN 'Medium Risk'
    WHEN Average_Outage_Duration_In_Days <= 0.5 THEN 'Low Risk'
    ELSE 'N/A'
END as Risk_Classification
FROM CTE_risk;

 * sqlite:///AEMR.db
Done.

[('AURICON', 2017, 616, 0.06, 'Low Risk'),
 ('GW', 2016, 323, 0.38, 'Low Risk'),
 ('GW', 2017, 238, 1.02, 'High Risk'),
 ('AURICON', 2016, 225, 0.12, 'Low Risk'),
 ('AUXC', 2016, 208, 0.08, 'Low Risk'),
 ('MELK', 2017, 180, 2.25, 'High Risk'),
 ('TRMOS', 2017, 179, 0.4, 'Low Risk'),
 ('MELK', 2016, 170, 0.85, 'Medium Risk'),
 ('PUG', 2017, 149, 0.22, 'Low Risk'),
 ('AUXC', 2017, 124, 0.02, 'Low Risk'),
 ('PJRH', 2016, 81, 1.22, 'High Risk'),
 ('KORL', 2017, 79, 1.34, 'High Risk'),
 ('PJRH', 2017, 75, 0.89, 'Medium Risk'),
 ('PMC', 2016, 72, 0.48, 'Low Risk'),
 ('TRMOS', 2016, 67, 0.2, 'Low Risk'),
 ('COLLGAR', 2017, 55, 1.21, 'High Risk'),
 ('KORL', 2016, 53, 0.38, 'Low Risk'),
 ('PMC', 2017, 49, 0.04, 'Low Risk'),
 ('COLLGAR', 2016, 40, 0.98, 'Medium Risk'),
 ('ENRG', 2016, 27, 1.95, 'High Risk'),
 ('PUG', 2016, 26, 0.85, 'Medium Risk'),
 ('EUCT', 2016, 20, 3.42, 'High Risk'),
 ('STHRNCRS', 2017, 18, 0.26, 'Low Risk'),
 ('STHRNCRS', 2016, 16, 0.32, 'Low Risk'),
 ('MUND', 2017, 16, 0.18, 'Low Risk'),
 ('MCG', 2017, 13, 0.26, 'Low Risk'),
 ('WGUTD', 2017, 8, 3.44, 'High Risk'),
 ('ENRG', 2017, 7, 0.26, 'Low Risk'),
 ('MCG', 2016, 5, 0.28, 'Low Risk'),
 ('TSLA_MGT', 2016, 5, 0.19, 'Low Risk'),
 ('EUCT', 2017, 5, 0.23, 'Low Risk'),
 ('TSLA_MGT', 2017, 5, 0.25, 'Low Risk'),
 ('MUND', 2016, 4, 0.37, 'Low Risk'),
 ('WGUTD', 2016, 3, 0.35, 'Low Risk'),
 ('DNHR', 2016, 1, 0.4, 'Low Risk'),
 ('DNHR', 2017, 1, 0.48, 'Low Risk')]

<h3 style = "color:#5D3FD3"> findings </h3>

Now that we've classified our participants as either `High Risk`, `Medium Risk` or `Low Risk`, we want to dig a little deeper.

Does it make sense that `Consequential`, `Opportunistic` or `Planned` aren't considered regarding the Risk Category?

Perhaps we should refine our category accordingly by ensuring we focus our Risk Category on labelling only `Forced` Outages as being a Risk. After all, Forced Outages are the unplanned outages that risk the security of the electricity grid.

Let's add two additional criteria to our classification considering `Total Number of Outage Events` and `Outage Type`.

We've summarised these below:

<b>
<li> High Risk - On average, the participant is unavailable for > 24 Hours (1 Day) OR the Total Number of Outage Events > 20 </li>
<li> Medium Risk - On average, the participant is unavailable between 12 and 24 Hours OR the Total Number of Outage Events is Between 10 and 20 </li>
<li> Low Risk - On average, the participant is unavailable for less than 12 Hours OR the Total Number of Outage Events < 10 </li> 
<li> If Outage Type is not forced, then N/A
</b>

<h3 style="color:#D4AF37"> Question Five </h3>

<b> Write a SQL Statement that <u> classifies each participant code as either `High Risk`, `Medium Risk` or `Low Risk` in a column called `Risk_Classification`</u> using the new classification criteria. Order the results using `Average Duration Time In Days` in descending order.

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [350]:
%%sql
WITH CTE_risk AS(
SELECT
Participant_Code, 
Outage_Reason, 
Year, 
COUNT(*) as Total_Number_Outage_Events,
ROUND(AVG((ABS(JULIANDAY(End_Time) - JULIANDAY(Start_Time)))),2) as Average_Outage_Duration_In_Days

FROM AEMR_Outage_Table
WHERE Status = 'Approved' 

GROUP BY Outage_Reason, Year, Participant_Code
ORDER BY Total_Number_Outage_Events DESC
)

SELECT *,
CASE
    WHEN Average_Outage_Duration_In_Days >= 1 OR Total_Number_Outage_Events > 20 THEN 'High Risk'
    WHEN Average_Outage_Duration_In_Days BETWEEN 0.5 AND 1 OR Total_Number_Outage_Events BETWEEN 10 AND 20 THEN 'Medium Risk'
    WHEN Average_Outage_Duration_In_Days <= 0.5 OR Total_Number_Outage_Events <=10 THEN 'Low Risk'
    ELSE 'N/A' END 
    as Risk_Classification
FROM CTE_risk
WHERE Outage_Reason = 'Forced'
ORDER BY Average_Outage_Duration_In_Days DESC
LIMIT 10;

 * sqlite:///AEMR.db
Done.

[('EUCT', 'Forced', 2016, 11, 5.9, 'High Risk'),
 ('WGUTD', 'Forced', 2017, 8, 3.44, 'High Risk'),
 ('MELK', 'Forced', 2017, 177, 2.28, 'High Risk'),
 ('ENRG', 'Forced', 2016, 21, 2.24, 'High Risk'),
 ('COLLGAR', 'Forced', 2017, 45, 1.38, 'High Risk'),
 ('PJRH', 'Forced', 2016, 81, 1.22, 'High Risk'),
 ('KORL', 'Forced', 2017, 76, 1.21, 'High Risk'),
 ('COLLGAR', 'Forced', 2016, 29, 1.11, 'High Risk'),
 ('GW', 'Forced', 2017, 227, 1.06, 'High Risk'),
 ('PUG', 'Forced', 2016, 24, 0.92, 'High Risk')]

<h4 style = "color:#5D3FD3"> Findings: this code finds out who have longest duration with High risk classification.  </h4>

<h3 style="color:#D4AF37"> ‚ö° Part II. Energy Losses & Market Reliability ‚ö° </h3>

When an energy provider provides energy to the market, they are making a commitment to the market and saying; ‚ÄúWe will supply X amount of energy to the market under a contractual obligation.‚Äù However, in a situation where the outages are Forced, the energy provider intended to provide energy but are unable to provide energy and are forced offline. <b style="color:Maroon">If many energy providers are forced offline at the same time it could cause an energy security risk that AEMR needs to mitigate. </b>

To ensure this doesn‚Äôt happen, the AEMR is interested in exploring the following questions:

<li> Of the outage types in 2016 and 2017, what percent were Forced Outage(s)?
<li> What was the average duration for a forced outage during both 2016 and 2017? Have we seen an increase in the average duration of forced outages?
<li> Which energy providers tended to have the largest number of forced outages?
    
<p>

<b> We'll examine this in the questions below. </b>
    
<img src = "https://media.istockphoto.com/id/1281821795/photo/market-stock-graph-and-information-with-city-light-and-electricity-and-energy-facility-banner.jpg?s=612x612&w=0&k=20&c=RSN5LqeMW28HW10aA190_DWR5YJ5tG2wixHFPBV3uZE=">

<h3 style="color:#D4AF37"> Question Six </h3>

<b> Write a SQL Statement to calculate the proportion of Forced Outages that have occurred over the 2016 - 2017 Period.
Do we observe any particular increases regarding any Outage Types over this period? </b>

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [347]:
%%sql
SELECT
Year,
COUNT(*) as Total_Number_Outages,
SUM(CASE 
    WHEN Outage_Reason = 'Forced' THEN 1 ELSE 0 END) as Total_Number_Forced_Outage_Events,

ROUND(SUM(CASE WHEN Outage_Reason = 'Forced' THEN 1 ELSE 0 END)*1.0 / COUNT(*)*100, 2) as Pct_Outage_Forced

FROM AEMR_Outage_Table
WHERE Status = 'Approved'
GROUP BY Year;

 * sqlite:///AEMR.db
Done.

[(2016, 1931, 1264, 65.46), (2017, 2171, 1622, 74.71)]

<h4 style = "color:#5D3FD3"> Findings: Percentage of outage is increasing since 2016.</h4>

Great. It's clear to see now that `Forced Outages` are problematic for us. Not only are they the only outage type that generates financial losses as the Outage is unplanned, it seems there is a number of Energy Participants who have been having a significantly high number of Outages.

Now what can we do about this? 

Let's break our analysis down into Macro and Micro Analysis.
The total gives us the Overall Duration a participant is offline / has lost energy, however, it doesn't tell us how *frequently* this occurs. In other words, if we have one or two very big outages, it might contribute to very large totals.

However, perhaps an <b> average </b> can help us identify how big these Outages might really be, spread across the year!

Let's take a look.

<h3 style="color:#D4AF37"> Question Seven </h3>

Write a SQL Statement to calculate the `Total Number of Outages`, `Total Duration In Days`and `Total Energy Lost` of all valid `Outages` for each `participant code` and `facility_code`, sorted by `Total Energy Lost` in descending order and Ordered by the YEAR Category.

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [270]:
%%sql
SELECT
COUNT(*) as Total_Number_Outages,
ROUND(SUM(ABS(JULIANDAY(End_Time) - JULIANDAY(Start_Time))),2) as Total_Duration_In_Days,
ROUND(SUM(Energy_Lost_MW),2) as Total_Energy_Lost,
Outage_Reason,
Participant_Code,
Facility_Code,
Year
FROM AEMR_Outage_Table
WHERE Status = 'Approved'
GROUP BY Year, Facility_Code, Participant_Code, Outage_Reason
ORDER BY Total_Energy_Lost DESC, Year DESC;

 * sqlite:///AEMR.db
Done.

[(490, 33.65, 21639.55, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (227, 240.69, 19326.56, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (317, 120.6, 15751.38, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (157, 129.6, 13771.07, 'Forced', 'MELK', 'MELK_G7', 2016),
 (208, 15.06, 10696.28, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (177, 404.15, 10285.4, 'Forced', 'MELK', 'MELK_G7', 2017),
 (85, 392.25, 9668.79, 'Scheduled (Planned)', 'MELK', 'MELK_G7', 2016),
 (69, 34.06, 9093.08, 'Forced', 'PMC', 'PMC_AG', 2016),
 (70, 482.58, 7499.28, 'Scheduled (Planned)', 'MELK', 'MELK_G7', 2017),
 (46, 87.02, 6964.8, 'Scheduled (Planned)', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (45, 199.4, 6450.0, 'Scheduled (Planned)', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (45, 65.4, 5941.25, 'Scheduled (Planned)', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (81, 98.79, 5881.52, 'Forced', 'PJRH', 'PJRH_GT11', 2016),
 (40, 1.56, 5648.44, 'Forced', 'PMC', 'PMC_AG', 2017),
 (172, 71.9, 5016.67, 'Forced', 'TRMOS', 'TIWEST_COG1', 2017),
 (72, 60.13, 4839.28, 'Forced', 'PJRH', 'PJRH_GT11', 2017),
 (27, 51.4, 4839.0, 'Scheduled (Planned)', 'PMC', 'PMC_AG', 2016),
 (76, 91.79, 4679.68, 'Forced', 'KORL', 'KORL_GT3', 2017),
 (29, 32.33, 4320.86, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (135, 33.4, 4112.1, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2017),
 (53, 20.0, 4040.32, 'Forced', 'KORL', 'KORL_GT3', 2016),
 (41, 5.31, 3925.55, 'Consequential', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (26, 68.9, 3812.42, 'Scheduled (Planned)', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (39, 9.17, 3100.95, 'Opportunistic Maintenance (Planned)', 'PJRH', 'PJRH_GT11', 2017),
 (20, 6.21, 2951.0, 'Opportunistic Maintenance (Planned)', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (24, 17.0, 2877.04, 'Opportunistic Maintenance (Planned)', 'MELK', 'MELK_G7', 2016),
 (45, 62.1, 2787.06, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (206, 16.04, 2734.14, 'Forced', 'AUXC', 'AUXC_WGP', 2016),
 (42, 8.88, 2553.24, 'Consequential', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (38, 89.9, 2445.0, 'Scheduled (Planned)', 'PJRH', 'PJRH_GT11', 2016),
 (23, 4.21, 2178.95, 'Opportunistic Maintenance (Planned)', 'PJRH', 'PJRH_GT11', 2016),
 (12, 51.38, 2139.87, 'Scheduled (Planned)', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (35, 91.35, 2110.01, 'Scheduled (Planned)', 'PJRH', 'PJRH_GT11', 2017),
 (120, 2.1, 1768.76, 'Forced', 'AUXC', 'AUXC_WGP', 2017),
 (20, 139.25, 1685.6, 'Scheduled (Planned)', 'KORL', 'KORL_GT3', 2016),
 (8, 28.15, 1672.66, 'Consequential', 'PMC', 'PMC_AG', 2017),
 (12, 20.35, 1639.2, 'Scheduled (Planned)', 'PMC', 'PMC_AG', 2017),
 (9, 57.27, 1632.78, 'Scheduled (Planned)', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (7, 5.35, 1524.82, 'Consequential', 'MELK', 'MELK_G7', 2016),
 (13, 3.67, 1423.53, 'Opportunistic Maintenance (Planned)', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (12, 7.15, 1374.0, 'Consequential', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (16, 10.44, 1339.7, 'Opportunistic Maintenance (Planned)', 'MELK', 'MELK_G7', 2017),
 (16, 23.56, 1334.0, 'Scheduled (Planned)', 'PUG', 'PERTHENERGY_KORL_GT1', 2016),
 (16, 54.1, 1326.6, 'Scheduled (Planned)', 'KORL', 'KORL_GT3', 2017),
 (65, 12.63, 1232.43, 'Forced', 'TRMOS', 'TIWEST_COG1', 2016),
 (21, 47.04, 1182.8, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (14, 3.04, 1172.05, 'Opportunistic Maintenance (Planned)', 'KORL', 'KORL_GT3', 2016),
 (11, 24.73, 1160.0, 'Scheduled (Planned)', 'PUG', 'PERTHENERGY_KORL_GT1', 2017),
 (5, 1.17, 926.0, 'Consequential', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (10, 2.42, 842.8, 'Opportunistic Maintenance (Planned)', 'KORL', 'KORL_GT3', 2017),
 (20, 3.6, 832.72, 'Consequential', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (24, 22.17, 815.47, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2016),
 (5, 1.65, 763.96, 'Opportunistic Maintenance (Planned)', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (28, 27.75, 678.4, 'Scheduled (Planned)', 'TSLA_MGT', 'TESLA_PICTON_G1', 2017),
 (18, 63.46, 664.0, 'Scheduled (Planned)', 'MUND', 'MUNDARING_GT1', 2016),
 (10, 2.81, 643.0, 'Consequential', 'PMC', 'PMC_AG', 2016),
 (7, 1.48, 580.0, 'Opportunistic Maintenance (Planned)', 'PUG', 'PERTHENERGY_KORL_GT1', 2016),
 (12, 3.4, 563.33, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2017),
 (3, 0.98, 523.0, 'Opportunistic Maintenance (Planned)', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (37, 183.58, 516.92, 'Scheduled (Planned)', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2017),
 (6, 13.42, 505.95, 'Consequential', 'KORL', 'KORL_GT3', 2017),
 (23, 45.25, 448.8, 'Scheduled (Planned)', 'TSLA_MGT', 'TESLA_PICTON_G1', 2016),
 (29, 140.6, 445.6, 'Scheduled (Planned)', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (15, 2.85, 398.58, 'Forced', 'MUND', 'MUNDARING_GT1', 2017),
 (3, 0.71, 348.0, 'Opportunistic Maintenance (Planned)', 'PUG', 'PERTHENERGY_KORL_GT1', 2017),
 (9, 1.9, 335.86, 'Opportunistic Maintenance (Planned)', 'MUND', 'MUNDARING_GT1', 2017),
 (1, 0.25, 335.0, 'Opportunistic Maintenance (Planned)', 'PMC', 'PMC_AG', 2017),
 (1, 0.08, 335.0, 'Opportunistic Maintenance (Planned)', 'PMC', 'PMC_AG', 2016),
 (14, 9.46, 322.0, 'Scheduled (Planned)', 'STHRNCRS', 'STHRNCRS_EG', 2017),
 (13, 4.29, 299.0, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2016),
 (13, 8.04, 299.0, 'Scheduled (Planned)', 'STHRNCRS', 'STHRNCRS_EG', 2016),
 (30, 13.21, 297.0, 'Consequential', 'TSLA_MGT', 'TESLA_PICTON_G1', 2016),
 (18, 4.65, 292.7, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2017),
 (17, 6.96, 290.4, 'Consequential', 'EUCT', 'GRASMERE_WF1', 2016),
 (7, 11.9, 262.46, 'Scheduled (Planned)', 'MUND', 'MUNDARING_GT1', 2017),
 (8, 1.21, 248.0, 'Opportunistic Maintenance (Planned)', 'MUND', 'MUNDARING_GT1', 2016),
 (23, 7.73, 227.7, 'Consequential', 'TSLA_MGT', 'TESLA_PICTON_G1', 2017),
 (14, 4.52, 222.3, 'Consequential', 'EUCT', 'GRASMERE_WF1', 2017),
 (8, 27.54, 221.29, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (4, 0.23, 220.0, 'Scheduled (Planned)', 'MCG', 'MWF_MUMBIDA_WF1', 2017),
 (9, 1.94, 207.0, 'Consequential', 'STHRNCRS', 'STHRNCRS_EG', 2016),
 (6, 11.96, 198.0, 'Consequential', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2016),
 (7, 1.85, 191.86, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2017),
 (4, 1.23, 169.9, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2017),
 (4, 9.23, 168.4, 'Scheduled (Planned)', 'TRMOS', 'TIWEST_COG1', 2017),
 (5, 7.08, 168.4, 'Scheduled (Planned)', 'TRMOS', 'TIWEST_COG1', 2016),
 (15, 8.48, 161.4, 'Consequential', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (2, 0.5, 160.0, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2016),
 (4, 1.48, 147.2, 'Forced', 'MUND', 'MUNDARING_GT1', 2016),
 (2, 0.52, 110.0, 'Consequential', 'MCG', 'MWF_MUMBIDA_WF1', 2016),
 (2, 0.46, 94.0, 'Consequential', 'MCG', 'MWF_MUMBIDA_WF1', 2017),
 (4, 0.96, 89.29, 'Consequential', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (4, 1.9, 87.0, 'Opportunistic Maintenance (Planned)', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (2, 0.1, 72.0, 'Opportunistic Maintenance (Planned)', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (3, 0.1, 64.8, 'Forced', 'EUCT', 'GRASMERE_WF1', 2017),
 (11, 64.9, 64.8, 'Forced', 'EUCT', 'GRASMERE_WF1', 2016),
 (7, 1.87, 63.8, 'Consequential', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2017),
 (1, 0.79, 55.0, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2016),
 (1, 1.42, 55.0, 'Scheduled (Planned)', 'MCG', 'MWF_MUMBIDA_WF1', 2016),
 (2, 0.04, 54.0, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2016),
 (2, 2.5, 50.0, 'Scheduled (Planned)', 'AUXC', 'AUXC_WGP', 2016),
 (2, 0.52, 46.0, 'Consequential', 'STHRNCRS', 'STHRNCRS_EG', 2017),
 (1, 0.04, 36.0, 'Consequential', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (1, 10.58, 36.0, 'Scheduled (Planned)', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (1, 0.6, 36.0, 'Opportunistic Maintenance (Planned)', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2016),
 (1, 0.1, 26.0, 'Consequential', 'AUXC', 'AUXC_WGP', 2017),
 (1, 2.88, 26.0, 'Scheduled (Planned)', 'AUXC', 'AUXC_WGP', 2017),
 (1, 0.96, 25.0, 'Consequential', 'AUXC', 'AUXC_WGP', 2016),
 (3, 1.04, 24.1, 'Opportunistic Maintenance (Planned)', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2017),
 (1, 0.06, 23.0, 'Opportunistic Maintenance (Planned)', 'STHRNCRS', 'STHRNCRS_EG', 2017),
 (12, 2.9, 17.28, 'Consequential', 'DNHR', 'DNHR_DENMARK_WF1', 2017),
 (11, 3.12, 15.84, 'Consequential', 'DNHR', 'DNHR_DENMARK_WF1', 2016),
 (1, 0.48, 1.44, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2017),
 (1, 0.4, 1.44, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2016),
 (1, 0.06, 0.0, 'Opportunistic Maintenance (Planned)', 'TRMOS', 'TIWEST_COG1', 2016)]

In [344]:
%%sql
SELECT
COUNT(*) as Total_Number_Outages,
ROUND(SUM(ABS(JULIANDAY(End_Time) - JULIANDAY(Start_Time))),2) as Total_Duration_In_Days,
ROUND(SUM(Energy_Lost_MW),2) as Total_Energy_Lost,
Participant_Code,
Facility_Code,
Year
FROM AEMR_Outage_Table
WHERE Outage_Reason = 'Forced'
GROUP BY Facility_Code, Participant_Code,Year
ORDER BY Total_Energy_Lost DESC, Year DESC;

 * sqlite:///AEMR.db
Done.

[(616, 37.5, 30820.22, 'AURICON', 'AURICON_PNJ_U1', 2017),
 (238, 242.98, 20237.03, 'GW', 'BW1_GREENWATERS_G2', 2017),
 (323, 121.46, 16138.37, 'GW', 'BW1_GREENWATERS_G2', 2016),
 (170, 143.83, 15886.67, 'MELK', 'MELK_G7', 2016),
 (225, 26.81, 11949.19, 'AURICON', 'AURICON_PNJ_U1', 2016),
 (180, 404.52, 10903.1, 'MELK', 'MELK_G7', 2017),
 (72, 34.46, 9229.08, 'PMC', 'PMC_AG', 2016),
 (49, 2.08, 7284.86, 'PMC', 'PMC_AG', 2017),
 (81, 98.79, 5881.52, 'PJRH', 'PJRH_GT11', 2016),
 (179, 72.44, 5227.0, 'TRMOS', 'TIWEST_COG1', 2017),
 (40, 39.19, 5188.86, 'COLLGAR', 'COLLGAR_WF1', 2016),
 (75, 67.1, 4998.58, 'PJRH', 'PJRH_GT11', 2017),
 (79, 106.17, 4881.21, 'KORL', 'KORL_GT3', 2017),
 (149, 33.4, 4395.2, 'PUG', 'PERTHENERGY_KORL_GT1', 2017),
 (53, 20.0, 4040.32, 'KORL', 'KORL_GT3', 2016),
 (55, 66.38, 3591.06, 'COLLGAR', 'COLLGAR_WF1', 2017),
 (208, 16.04, 2775.28, 'AUXC', 'AUXC_WGP', 2016),
 (124, 2.1, 1821.71, 'AUXC', 'AUXC_WGP', 2017),
 (67, 13.13, 1316.63, 'TRMOS', 'TIWEST_COG1', 2016),
 (27, 52.77, 1250.8, 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (26, 22.17, 863.4, 'PUG', 'PERTHENERGY_KORL_GT1', 2016),
 (13, 3.4, 590.83, 'MCG', 'MWF_MUMBIDA_WF1', 2017),
 (16, 2.94, 417.18, 'MUND', 'MUNDARING_GT1', 2017),
 (16, 5.13, 368.0, 'STHRNCRS', 'STHRNCRS_EG', 2016),
 (18, 4.65, 292.7, 'STHRNCRS', 'STHRNCRS_EG', 2017),
 (5, 1.42, 249.8, 'MCG', 'MWF_MUMBIDA_WF1', 2016),
 (8, 27.54, 221.29, 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (20, 68.4, 215.4, 'EUCT', 'GRASMERE_WF1', 2016),
 (7, 1.85, 191.86, 'ENRG', 'ENRG_KALGOORLIE_GT3', 2017),
 (5, 0.94, 189.7, 'TSLA_MGT', 'TESLA_PICTON_G1', 2016),
 (5, 1.25, 179.8, 'TSLA_MGT', 'TESLA_PICTON_G1', 2017),
 (4, 1.48, 147.2, 'MUND', 'MUNDARING_GT1', 2016),
 (5, 1.15, 100.2, 'EUCT', 'GRASMERE_WF1', 2017),
 (3, 1.04, 90.0, 'WGUTD', 'WEST_KALGOORLIE_GT2', 2016),
 (1, 0.48, 1.44, 'DNHR', 'DNHR_DENMARK_WF1', 2017),
 (1, 0.4, 1.44, 'DNHR', 'DNHR_DENMARK_WF1', 2016)]

<h4 style = "color:#5D3FD3"> Findings:the top 3 participants with massive energy loss are AURICON,MELK,GW. </h4>

<h3 style="color:#D4AF37"> Question Eight </h3>

<b> Write a SQL Statement to calculate the `Average Duration In Days`and `Average Energy Lost` of all valid `FORCED OUTAGES` for each `participant code` and `facility_code` sorted by `Average Energy Lost` in descending order and Ordered by the YEAR Category.

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [300]:
%%sql
SELECT
ROUND(AVG(ABS(JULIANDAY(End_Time) - JULIANDAY(Start_Time))),2) as Avg_Duration_In_Days,
ROUND(AVG(Energy_Lost_MW),2) as Avg_Energy_Lost,
Outage_Reason,
Participant_Code,
Facility_Code,
Year

FROM AEMR_Outage_Table
WHERE Outage_Reason = 'Forced'
GROUP BY Participant_Code, Facility_Code, Year
ORDER BY Avg_Duration_In_Days DESC
LIMIT 10;

 * sqlite:///AEMR.db
Done.

[(3.44, 27.66, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (3.42, 10.77, 'Forced', 'EUCT', 'GRASMERE_WF1', 2016),
 (2.25, 60.57, 'Forced', 'MELK', 'MELK_G7', 2017),
 (1.95, 46.33, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (1.34, 61.79, 'Forced', 'KORL', 'KORL_GT3', 2017),
 (1.22, 72.61, 'Forced', 'PJRH', 'PJRH_GT11', 2016),
 (1.21, 65.29, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (1.02, 85.03, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (0.98, 129.72, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (0.89, 66.65, 'Forced', 'PJRH', 'PJRH_GT11', 2017)]

<h4 style = "color:#5D3FD3"> Findings: The top three grid providers with the longest outage durations are WGUTD, EUCT, and MELK. However, energy loss is not directly correlated with longer outage durations. </h4>

<h3 style="color:#D4AF37"> Question Nine </h3>

<b> Write a SQL Statement to calculate the `Average Energy Lost` and `Total Energy Lost` for each `Facility Code` and `Participant Code` across both the 2016 and 2017 periods when the `Outage_Reason` is set to Forced. Upon completion of this, calculate the <u> percentage </u> of energy lost due to forced outages for each `Facility_Code`. Please ORDER the query by `Total Energy Lost` from 2016 to 2017.
    
From your analysis, which participants have contributed the most to the Energy Lost due to Forced Outages?

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [334]:
%%sql
SELECT
ROUND(AVG(Energy_Lost_MW),2) as Avg_Energy_Lost,
ROUND(SUM(Energy_Lost_MW),2) as Total_Energy_Lost,
ROUND(SUM(Energy_Lost_MW) / (SELECT SUM(Energy_Lost_MW) FROM AEMR_Outage_Table WHERE Status = 'Approved' AND Outage_Reason = 'Forced')*100,2) as Pct_Energy_Loss,
Outage_Reason,
Participant_Code,
Facility_Code,
Year

FROM AEMR_Outage_Table
WHERE Outage_Reason = 'Forced' AND Status = 'Approved'
GROUP BY Participant_Code, Facility_Code, Year
ORDER BY Total_Energy_Lost DESC;

 * sqlite:///AEMR.db
Done.

[(44.16, 21639.55, 14.21, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (85.14, 19326.56, 12.69, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (49.69, 15751.38, 10.34, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (87.71, 13771.07, 9.04, 'Forced', 'MELK', 'MELK_G7', 2016),
 (51.42, 10696.28, 7.02, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (58.11, 10285.4, 6.75, 'Forced', 'MELK', 'MELK_G7', 2017),
 (131.78, 9093.08, 5.97, 'Forced', 'PMC', 'PMC_AG', 2016),
 (72.61, 5881.52, 3.86, 'Forced', 'PJRH', 'PJRH_GT11', 2016),
 (141.21, 5648.44, 3.71, 'Forced', 'PMC', 'PMC_AG', 2017),
 (29.17, 5016.67, 3.29, 'Forced', 'TRMOS', 'TIWEST_COG1', 2017),
 (67.21, 4839.28, 3.18, 'Forced', 'PJRH', 'PJRH_GT11', 2017),
 (61.57, 4679.68, 3.07, 'Forced', 'KORL', 'KORL_GT3', 2017),
 (149.0, 4320.86, 2.84, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (30.46, 4112.1, 2.7, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2017),
 (76.23, 4040.32, 2.65, 'Forced', 'KORL', 'KORL_GT3', 2016),
 (61.93, 2787.06, 1.83, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (13.27, 2734.14, 1.8, 'Forced', 'AUXC', 'AUXC_WGP', 2016),
 (14.74, 1768.76, 1.16, 'Forced', 'AUXC', 'AUXC_WGP', 2017),
 (18.96, 1232.43, 0.81, 'Forced', 'TRMOS', 'TIWEST_COG1', 2016),
 (56.32, 1182.8, 0.78, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (33.98, 815.47, 0.54, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2016),
 (46.94, 563.33, 0.37, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2017),
 (26.57, 398.58, 0.26, 'Forced', 'MUND', 'MUNDARING_GT1', 2017),
 (23.0, 299.0, 0.2, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2016),
 (16.26, 292.7, 0.19, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2017),
 (27.66, 221.29, 0.15, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (27.41, 191.86, 0.13, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2017),
 (42.48, 169.9, 0.11, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2017),
 (80.0, 160.0, 0.11, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2016),
 (36.8, 147.2, 0.1, 'Forced', 'MUND', 'MUNDARING_GT1', 2016),
 (5.89, 64.8, 0.04, 'Forced', 'EUCT', 'GRASMERE_WF1', 2016),
 (21.6, 64.8, 0.04, 'Forced', 'EUCT', 'GRASMERE_WF1', 2017),
 (55.0, 55.0, 0.04, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2016),
 (27.0, 54.0, 0.04, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2016),
 (1.44, 1.44, 0.0, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2016),
 (1.44, 1.44, 0.0, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2017)]

<h3 style = "color:#5D3FD3"> Findings: </h3>

<h3 style="color:#D4AF37"> Question Ten </h3>

<b>Having identified the top 3 participants by Total Energy Loss being `GW`, `MELK` and `Auricon`; Write a SQL Statement calculating the `Total_Energy_Lost` each of these three `Participant_Codes` and the `Facility_Code`. Additionally, identify the `Description_Of_Outage` associated with the highest `Total_Energy_Lost` for each of the `Participant_Codes` and `Facility_Code` for each of the three participants. 
    
<u>Lastly, calculate the percentage of Energy Loss, attributed to these reasons!</u> </b>

<b> ‚ö†Ô∏è Hint: As this is the final question, this is a bit of a <b> challenge question </b> which will involve some SQL functions you're not familiar with just yet. In the workplace, you're going to have to grow familiar with googling and searching for functions that you may have not learned or be familiar with. In this question, to identify the TOP `Description_Of_Outage` reason for each Participant, you're going to need to use `PARTITION BY`. You can read all about the approach you can take in this example <a href = "https://learnsql.com/cookbook/how-to-rank-rows-within-a-partition-in-sql/#:~:text=To%20partition%20rows%20and%20rank,rank%20rows%20within%20a%20partition."> here </a>. Good luck!

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [336]:
%%sql
SELECT *
FROM(
SELECT
Participant_Code,
Facility_Code,
Description_Of_Outage,
ROUND(AVG(ABS(JULIANDAY(End_Time) - JULIANDAY(Start_Time))),2) as AVG_Duration_In_Days,
ROUND(SUM(Energy_Lost_MW), 2) as Total_Energy_Lost,
ROUND(SUM(Energy_Lost_MW) / (SELECT SUM(Energy_Lost_MW) FROM AEMR_Outage_Table WHERE Status = 'Approved' AND Outage_Reason = 'Forced')*100,2) as Pct_Energy_Loss,
RANK() OVER (PARTITION BY Participant_Code, Facility_Code ORDER BY SUM(Energy_Lost_MW) DESC) as Rank_MW_Lost
FROM AEMR_Outage_Table
WHERE Participant_Code IN ('GW', 'MELK', 'AURICON') AND Status= 'Approved' AND Outage_Reason = 'Forced'
GROUP BY Participant_Code, Facility_Code, Description_Of_Outage
ORDER BY Participant_Code, Total_Energy_Lost DESC)

WHERE Rank_MW_Lost = 1

 * sqlite:///AEMR.db
Done.

[('AURICON', 'AURICON_PNJ_U1', 'Full unit trip', 0.0, 6033.87, 3.96, 1),
 ('GW', 'BW1_GREENWATERS_G2', 'Operational Issues caused real time forced outage.', 0.61, 28687.54, 18.84, 1),
 ('MELK', 'MELK_G7', 'Safety Issues', 11.65, 1100.0, 0.72, 1)]

<h3 style = "color:#5D3FD3"> Findings: this code list the top 3 participants with the longest avg. durations</h3>

That's a Wrap! I've now analyzed all the data I need to answer Management's Questions.
The next part of my analysis where I'll be proceeding with creating my story in Tableau using the insights I've gathered from my SQL Analysis! 

Let's now switch to Part II of Analysis in Tableau!!

<img src = https://www.energymagazine.com.au/wp-content/uploads/2021/05/shutterstock_1888482466-e1620278098312.jpg>